# Generated by Django 4.2.1 on 2023-07-18 08:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_cart_item'),
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='added_by',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='items',
            name='count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='items',
            name='image',
            field=models.ImageField(upload_to='uploads/'),
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('item_adder', models.CharField(default=None, max_length=30)),
                ('payment', models.CharField(default=None, max_length=50)),
                ('order_status', models.CharField(default='Delivered', max_length=60)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.items')),
                ('ordered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.purchaser')),
            ],
        ),
    ]
