# Generated by Django 4.2.1 on 2023-07-18 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_items_added_by_items_count_alter_items_image_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='order_status',
        ),
    ]
