# Generated by Django 4.2.1 on 2023-06-25 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_alter_items_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
