# Generated by Django 4.2.1 on 2023-07-08 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_items_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='added_by',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
