# Generated by Django 4.2.1 on 2023-07-15 02:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_cart_item'),
        ('seller', '0004_items_added_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.items')),
                ('ordered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.purchaser')),
            ],
        ),
    ]
