# Generated by Django 4.2.1 on 2023-07-18 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0004_orders_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_status',
            field=models.CharField(default='Placed Order', max_length=60),
        ),
    ]
