# Generated by Django 4.2.1 on 2023-07-18 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0005_alter_orders_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_status',
            field=models.CharField(choices=[('Placed Order', 'Placed Order'), ('Shipped', 'Shipped'), ('Out for Delivery', 'Out for Devilvery'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Placed Order', max_length=60),
        ),
    ]
