# Generated by Django 4.2.1 on 2023-06-26 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaser',
            name='cart',
        ),
        migrations.AddField(
            model_name='cart',
            name='item',
            field=models.CharField(default=None, max_length=150),
        ),
        migrations.AlterField(
            model_name='cart',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.purchaser'),
        ),
    ]
