# Generated by Django 4.2.1 on 2023-06-29 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_cart_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='item',
            field=models.CharField(default=None, max_length=150, unique=True),
        ),
    ]
